### ISSUE TITLE
Remove timeout on mutex locks

### ISSUE THREAD

**Issue by dorotaphanSiili** [apigear-io/objectlink-core-cpp#22]
throw an exception or log? 
should depend on some flag to throw or not to throw
connected to https://github.com/apigear-io/template-cpp14/issues/47 and  https://github.com/apigear-io/template-cpp14/issues/32

**Comment by w4bremer** [comment]
Agreed in discussion that we do not use timeout locks. Therefore re-write and remove the timeout locks from the implementation.
